 const AIType = {
    COMPLETIONS : 'COMPLETIONS',  
    IMAGES : 'IMAGES',
    AUDIO : 'AUDIO',
    TRANSCRIPTION : 'TRANSCRIPTION',
    IMAGETOTEXT : 'IMAGETOTEXT', 
    SUMMARIZATION : 'SUMMARIZATION',
    TRANSLATION : 'TRANSLATION',
    FILES : 'FILES',
    CHAT : 'CHAT',
    EMBEDDINGS : 'EMBEDDINGS',
    MODERATIONS : 'MODERATIONS',
    MODELS : 'MODELS',
    FINETUNING : 'FINETUNING',
    BETA : 'BETA',
    BATCHES : 'BATCHES',
    YOUTUBE_LINK : 'YOUTUBE_LINK' 
  }


  export default AIType;
   